name: Deploy Admin Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace Secrets
      run: |
        sed -i 's/{{ADMIN_NICKNAME}}/${{ secrets.SECRET_ADMIN_NICKNAME }}/g' admin.html
        sed -i 's/{{ADMIN_PASSWORD}}/${{ secrets.SECRET_ADMIN_PASSWORD }}/g' admin.html
        sed -i 's/{{SECURITY_ANSWER}}/${{ secrets.SECRET_SECURITY_ANSWER }}/g' admin.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
